### ISSUE TITLE
[Feature - Apr 1st, 2024] - {Common} ApiResult 제네릭으로 변경

### ISSUE THREAD

**Issue by numerical43** [cca-ffodregamdi/running-hi-back-v2#167]
✏️Description
-

- 안정성과 Swagger 설정을 위해 ApiResut의 Object 타입을 제네릭으로 변경

✅TODO
-
- [x]  ApiResut의 Object 타입을 제네릭으로 변경

🐾ETC
-

**Comment by Subak-Uncle** [comment]
감사합니다.
