### ISSUE TITLE
[Feature - May 4th, 2024] - {Deploy} 테스트 서버 S3 연결 및 배포 테스트

### ISSUE THREAD

**Issue by Subak-Uncle** [cca-ffodregamdi/running-hi-back-v2#254]
✏️Description
- IAM Role을 이용한 S3Client 연결과 더불어 배포 테스트를 진행하겠습니다.

✅TODO
- [x] 프로젝트 빌드 후 서버로 전송
- [x] postman을 이용한 테스트

🐾ETC
-

**Comment by Subak-Uncle** [comment]
성공적으로 마무리되었습니다!

**Comment by numerical43** [comment]
굿티비입니다!

**Comment by silverpoodle** [comment]
고생하셨습니다ㅜㅜ
