### ISSUE TITLE
Fix- [POST] 게시글 상세조회 시 난이도 추가

### ISSUE THREAD

**Issue by silverpoodle** [cca-ffodregamdi/running-hi-back-v2#389]
✏️Description
-
- 게시글 상세조회 시 Response 난이도 추가

✅TODO
- [x] GetPostResponse

🐾ETC
-

**Comment by Subak-Uncle** [comment]
Branch [feature/#389](https://github.com/cca-ffodregamdi/running-hi-back-v2/tree/feature/#389) created!
