### ISSUE TITLE
BugFix - [POST] 게시글 추천순 중복 오류 수정, 삭제 시 오류 수정

### ISSUE THREAD

**Issue by silverpoodle** [cca-ffodregamdi/running-hi-back-v2#395]
🗺️Location
-
- 게시글 API 버그 수정

🤷WHAT
-
- 게시글 추천순 정렬 시 중복 오류 발생
- 게시글 삭제 시 405 에러 발생
- 나의 게시글 페이징 수정

✏️HOW
-
어떻게 해결했는지

✅TODO
- [ ] PostService
- [ ] PostController

🐾ETC
-

**Comment by Subak-Uncle** [comment]
Branch [bugfix/#395](https://github.com/cca-ffodregamdi/running-hi-back-v2/tree/bugfix/#395) created!
