### ISSUE TITLE
Refactoring - 애플 로그인 로직 수정

### ISSUE THREAD

**Issue by numerical43** [cca-ffodregamdi/running-hi-back-v2#401]
✏️Description
-

- 기존의 로그인 방식은 RESTApi를 사용한 방식으로, 백엔드에서 애플 측으로 identity_token을 요청하고 처리하는 방식이지만 iOS에서는 프론트엔드에서 애플 측으로 identity_token을 요청하고 그 값을 백엔드로 전달하기 때문에 전체적인 로직을 수정

✅TODO
- [x] 애플 로그인 로직 수정 

🐾ETC
-

**Comment by Subak-Uncle** [comment]
Branch [refactor/#401](https://github.com/cca-ffodregamdi/running-hi-back-v2/tree/refactor/#401) created!
