### ISSUE TITLE
Refactoring - 챌린지 목표 컬럼 명칭 변경

### ISSUE THREAD

**Issue by hodin030** [cca-ffodregamdi/running-hi-back-v2#408]
✏️Description
-

챌린지 목표 컬럼 명칭 변경

✅TODO
- [x] 컬럼명 targetValue -> goal 로 변경

🐾ETC
-

**Comment by Subak-Uncle** [comment]
Branch [refactor/#408](https://github.com/cca-ffodregamdi/running-hi-back-v2/tree/refactor/#408) created!
