### ISSUE TITLE
BugFix - 더미데이터 생성 오류 수정

### ISSUE THREAD

**Issue by hodin030** [cca-ffodregamdi/running-hi-back-v2#410]
🗺️Location
-

/test/data

🤷WHAT
-
더미데이터 생성 시 오류 발생

✏️HOW
-
챌린지 컬럼명 수정 후 더미데이터 쿼리 부분 수정하지 않아 발생한 오류로, 쿼리 수정 후 해결

✅TODO
- [x] 챌린지 더미데이터 생성 쿼리 수정 

🐾ETC
-

**Comment by Subak-Uncle** [comment]
Branch [bugfix/#410](https://github.com/cca-ffodregamdi/running-hi-back-v2/tree/bugfix/#410) created!
