### ISSUE TITLE
Feature - 챌린지 컬럼 변경 및 더미데이터 추가

### ISSUE THREAD

**Issue by hodin030** [cca-ffodregamdi/running-hi-back-v2#415]
✏️Description
-

챌린지 컬럼 변경 및 더미데이터 추가

✅TODO
- [ ] 챌린지 컬럼 변경 및 더미데이터 추가

🐾ETC
-

**Comment by Subak-Uncle** [comment]
Branch [feature/#415](https://github.com/cca-ffodregamdi/running-hi-back-v2/tree/feature/#415) created!
