### ISSUE TITLE
BugFix - 챌린지 더미데이터 생성 오류 수정

### ISSUE THREAD

**Issue by hodin030** [cca-ffodregamdi/running-hi-back-v2#417]
🗺️Location
-

/test/data

🤷WHAT
-
어떤 문제가 발생했는지
더미데이터 생성시 500에러!!!

✏️HOW
-
쿼리가 잘못됐었다 -> 수정함

✅TODO
- [ ] 챌린지 더미데이터 생성 쿼리 수정

🐾ETC
-

**Comment by Subak-Uncle** [comment]
Branch [bugfix/#417](https://github.com/cca-ffodregamdi/running-hi-back-v2/tree/bugfix/#417) created!
