### ISSUE TITLE
Feature - [POST] 러닝 코스 GPS 정보 저장 시 수정사항

### ISSUE THREAD

**Issue by silverpoodle** [cca-ffodregamdi/running-hi-back-v2#422]
🗺️Location
-
- /api/v1/posts/gpx

🤷WHAT
-
- 500 에러

✏️HOW
-
어떻게 해결했는지

✅TODO
- [x] 위치 정보 받도록 설정
- [x] S3 문제 해결 전까지는 주석처리

🐾ETC
-

**Comment by Subak-Uncle** [comment]
Branch [bugfix/#422](https://github.com/cca-ffodregamdi/running-hi-back-v2/tree/bugfix/#422) created!
