### ISSUE TITLE
Refactoring - 챌린지 컬럼 변경, 챌린지 전체조회, 상세조회 API 변경

### ISSUE THREAD

**Issue by hodin030** [cca-ffodregamdi/running-hi-back-v2#423]
✏️Description
-

챌린지 컬럼 변경, 챌린지 전체조회, 상세조회 API 변경

✅TODO
- [x] 멤버가 참여중인 챌린지는 전체 챌린지 목록에서 조회되지 않도록 변경
- [x] 챌린지/멤버챌린지 상세조회 API 통합
- [x] 나의 챌린지쪽 변수명 통일
- [x] record랑 goal을 실수값으로 응답하도록 변경
- [x] goalDetail 컬럼 추가 (목표에 대한 추가 정보 String값)
- [x] 평균페이스 초단위로 응답하도록 변경

🐾ETC
-

**Comment by Subak-Uncle** [comment]
Branch [feature/#423](https://github.com/cca-ffodregamdi/running-hi-back-v2/tree/feature/#423) created!
