### ISSUE TITLE
Hotfix - [POST] 난이도 ENUM 명칭 수정

### ISSUE THREAD

**Issue by silverpoodle** [cca-ffodregamdi/running-hi-back-v2#427]
✏️Description
-
- 떼잉 분명히 했는데... 브랜치를 잘못설정했는지... 암튼 수정수정요
- VERYEASY, EASY, NORMAL, HARD, VERYHARD

✅TODO
- [x] Difficulty

🐾ETC
-

**Comment by Subak-Uncle** [comment]
Branch [feature/#427](https://github.com/cca-ffodregamdi/running-hi-back-v2/tree/feature/#427) created!
