### ISSUE TITLE
BugFix - [POST] 상세보기 좋아요, 북마크 개수 오류 확인

### ISSUE THREAD

**Issue by silverpoodle** [cca-ffodregamdi/running-hi-back-v2#429]
🗺️Location
-
- 상세보기 시 좋아요, 북마크 개수 오류 확인

🤷WHAT
-
어떤 문제가 발생했는지

✏️HOW
-
어떻게 해결했는지

✅TODO
- [x] PostQUeryImpl

🐾ETC
-

**Comment by Subak-Uncle** [comment]
Branch [bugfix/#429](https://github.com/cca-ffodregamdi/running-hi-back-v2/tree/bugfix/#429) created!
