### ISSUE TITLE
Refactoring - 챌린지 상세조회, 나의챌린지 상세조회 API 분리

### ISSUE THREAD

**Issue by hodin030** [cca-ffodregamdi/running-hi-back-v2#432]
✏️Description
-

챌린지 상세조회, 나의챌린지 상세조회 API 분리

✅TODO
- [x] 통합했던 두 API를 재분리
- [x] 나의 챌린지 상세조회 시 파라미터 변경(memberChallengeNo -> challengeNo)

🐾ETC
-

**Comment by Subak-Uncle** [comment]
Branch [feature/#432](https://github.com/cca-ffodregamdi/running-hi-back-v2/tree/feature/#432) created!
