### ISSUE TITLE
Feature - [POST] 게시글 저장&공유 방식 수정

### ISSUE THREAD

**Issue by silverpoodle** [cca-ffodregamdi/running-hi-back-v2#434]
✏️Description
-
- 러닝 기록 저장 후 공유 방식 수정

✅TODO
- [x] 구간별 기록 저장 기능
- [x] 기록 저장 시 장소, 난이도 추가

🐾ETC
-

**Comment by Subak-Uncle** [comment]
Branch [feature/#434](https://github.com/cca-ffodregamdi/running-hi-back-v2/tree/feature/#434) created!
