### ISSUE TITLE
BugFix - 애플 로그인 오류 수정

### ISSUE THREAD

**Issue by numerical43** [cca-ffodregamdi/running-hi-back-v2#436]
🗺️Location
-

- 클라이언트에서 애플 로그인 시 오류 발생

🤷WHAT
-

1. 포스트맨 상으로는 이미 사용된 authorizationCode라고 떴습니다.
  - 이미 iOS에 요청을 보내서 사용된 authorizationCode를 postman으로 사용하려고해서 뜬 메세지였습니다.
  - 현재 발생한 오류와 직접적으로 연관된 오류가 아니어서 다른 방법을 찾아봤습니다. 
2. 직접 xcode로 simulator를 돌리고 서버 console을 확인해보니 idToken이 null이라서 parsing할 수 없다는 메세지가 떴습니다. 

✏️HOW
-

- localhost로 바꿔서 연결하고, 로그를 통해 확인해보니 처음 요청이 들어올때 identityToken이 백엔드로 전달되지않아 null로 들어오고 있었습니다.
- 확인 결과, 프론트에서는 ```identityCode``` 로 전달하고 있었고, 백에서는 ```identityToken```으로 받고 있었습니다...
- 변수명을 수정하고 테스트하니 정상적으로 회원 가입, 회원 탈퇴가 이루어지는 것을 확인할 수 있었습니다. 

✅TODO
- [ ] 변수명 ```identityToken``` -> ```identityCode``` 로 수정

🐾ETC
-

**Comment by Subak-Uncle** [comment]
Branch [bugfix/#436](https://github.com/cca-ffodregamdi/running-hi-back-v2/tree/bugfix/#436) created!
