### ISSUE TITLE
Refactoring - 챌린지 랭킹 더미데이터 추가

### ISSUE THREAD

**Issue by hodin030** [cca-ffodregamdi/running-hi-back-v2#441]
✏️Description
-

챌린지 랭킹 더미데이터 추가

✅TODO
- [x] 챌린지에 랭킹 10명 이상 조회되도록 하는 더미데이터 추가

🐾ETC
-

**Comment by Subak-Uncle** [comment]
Branch [feature/#441](https://github.com/cca-ffodregamdi/running-hi-back-v2/tree/feature/#441) created!
