### ISSUE TITLE
Refactoring - 애플 로그인 변수명 변경 

### ISSUE THREAD

**Issue by numerical43** [cca-ffodregamdi/running-hi-back-v2#443]
✏️Description
-

- 애플에서 사용하는 용어에 맞게 변수명 변경

✅TODO
- [x] indentityCode -> identityToken으로 변경

🐾ETC
-

**Comment by Subak-Uncle** [comment]
Branch [feature/#443](https://github.com/cca-ffodregamdi/running-hi-back-v2/tree/feature/#443) created!
