### ISSUE TITLE
Feature - 챌린지 통합 정보 조회 API 생성

### ISSUE THREAD

**Issue by hodin030** [cca-ffodregamdi/running-hi-back-v2#446]
✏️Description
-

챌린지 통합 정보(전체 챌린지 수, 참여중인 챌린지 수, 챌린지 참여중인 회원 수) 조회 API 생성

✅TODO
- [ ] 전체 챌린지 수, 참여중인 챌린지 수, 챌린지 참여중인 회원 수 조회 서비스 로직 생성
- [ ] 챌린지 통합 정보 조회 컨트롤러 생성

🐾ETC
-

**Comment by Subak-Uncle** [comment]
Branch [feature/#446](https://github.com/cca-ffodregamdi/running-hi-back-v2/tree/feature/#446) created!
