### ISSUE TITLE
Refactoring - 레벨에 따른 거 증가 수정

### ISSUE THREAD

**Issue by numerical43** [cca-ffodregamdi/running-hi-back-v2#449]
✏️Description
-

- 레벨업 시 ```1.5배```씩 증가 시키던 거리량을 ```이전 거리 + 2km```로 수정
  - ex) 레벨 1 -> 2인 경우 2km, 레벨 2 -> 3인 경우 4km ... 

✅TODO
-
- [ ] 레벨업에 필요한 거리량 증가 수정

**Comment by Subak-Uncle** [comment]
Branch [feature/#449](https://github.com/cca-ffodregamdi/running-hi-back-v2/tree/feature/#449) created!
