### ISSUE TITLE
Feature - member 도메인 로깅

### ISSUE THREAD

**Issue by numerical43** [cca-ffodregamdi/running-hi-back-v2#450]
✏️Description
-

- member 도메인과 관련된 부분에 로깅 추가

✅TODO
-
- [x] member 도메인 로깅

🐾ETC
-

**Comment by Subak-Uncle** [comment]
Branch [feature/#450](https://github.com/cca-ffodregamdi/running-hi-back-v2/tree/feature/#450) created!
