### ISSUE TITLE
Feature - 기록 & 게시글 더미데이터 수정

### ISSUE THREAD

**Issue by silverpoodle** [cca-ffodregamdi/running-hi-back-v2#454]
✏️Description
-
- 러닝 기록 & 게시글 더미데이터 수정

✅TODO
- [x] 수정된 칼럼 적용
- [x] 카카오 & 애플 아이디 적용

🐾ETC
-

**Comment by Subak-Uncle** [comment]
Branch [feature/#454](https://github.com/cca-ffodregamdi/running-hi-back-v2/tree/feature/#454) created!
