### ISSUE TITLE
Fix -  기간별 러닝 기간 기록 조회 오류 수정

### ISSUE THREAD

**Issue by silverpoodle** [cca-ffodregamdi/running-hi-back-v2#456]
✏️Description
-
- 기간 별 러닝 기록 조회 시 러닝 제목 누락 수정

✅TODO
- [x] Response - title 누락
- [ ] 기록 전체 0으로 나오는 버그 수정

🐾ETC
-

**Comment by Subak-Uncle** [comment]
Branch [feature/#456](https://github.com/cca-ffodregamdi/running-hi-back-v2/tree/feature/#456) created!
