### ISSUE TITLE
Feature - 코스 기록 txt 파일로 저장하도록 수정

### ISSUE THREAD

**Issue by silverpoodle** [cca-ffodregamdi/running-hi-back-v2#460]
✏️Description
-
- 코스 기록 저장 시 txt 파일로 저장하도록 수정

✅TODO
- [x] postController
- [x] postService
- [x] uploadtoS3

🐾ETC
-

**Comment by Subak-Uncle** [comment]
Branch [feature/#460](https://github.com/cca-ffodregamdi/running-hi-back-v2/tree/feature/#460) created!
