### ISSUE TITLE
Feature - [RECORD] 기록 API response 수정

### ISSUE THREAD

**Issue by silverpoodle** [cca-ffodregamdi/running-hi-back-v2#485]
✏️Description
-

✅TODO
- [기록탭] 차트 바 눌렀을 때 위에뜨는 데이터 3개 필요함
    - Record API data 현재 [거리] 에서 [{거리, 시간,페이스,칼로리}] 로 변경 요청

🐾ETC
-

**Comment by Subak-Uncle** [comment]
Branch [feature/#485](https://github.com/cca-ffodregamdi/running-hi-back-v2/tree/feature/#485) created!
