### ISSUE TITLE
Refactoring - 불필요한 챌린지 더미데이터 삭제

### ISSUE THREAD

**Issue by hodin030** [cca-ffodregamdi/running-hi-back-v2#486]
✏️Description
- 불필요한 챌린지 더미데이터 삭제

✅TODO
- [x] 불필요한 챌린지 더미데이터 삭제

🐾ETC
-

**Comment by Subak-Uncle** [comment]
Branch [refactor/#486](https://github.com/cca-ffodregamdi/running-hi-back-v2/tree/refactor/#486) created!
