### ISSUE TITLE
Refactoring - 챌린지, 나의챌린지 전체조회 시 리턴값에 챌린지 개수 추가

### ISSUE THREAD

**Issue by hodin030** [cca-ffodregamdi/running-hi-back-v2#489]
✏️Description
-

챌린지, 나의챌린지 전체조회 시 리턴값에 챌린지 개수 추가

✅TODO
- [x] 리턴값에 챌린지 개수 추가

🐾ETC
-

**Comment by Subak-Uncle** [comment]
Branch [refactor/#489](https://github.com/cca-ffodregamdi/running-hi-back-v2/tree/refactor/#489) created!
