### ISSUE TITLE
Feature - [RECORD, POST] 기록, 게시글 상세보기 API response 수정

### ISSUE THREAD

**Issue by silverpoodle** [cca-ffodregamdi/running-hi-back-v2#491]
✏️Description
-

✅TODO
- [기록탭] 최근 운동 기록 눌렀을 때 게시글 상세보기 API 에서 
    - 위경도 리스트 추가 요청
- [기록탭] 최근 운동 기록 좌측 이미지
    - 어떤 이미지인지 결정 후 API로 해당값 추가 요청

🐾ETC
-

**Comment by Subak-Uncle** [comment]
Branch [feature/#491](https://github.com/cca-ffodregamdi/running-hi-back-v2/tree/feature/#491) created!
