### ISSUE TITLE
BugFix - 스케줄링 test 코드 수정

### ISSUE THREAD

**Issue by numerical43** [cca-ffodregamdi/running-hi-back-v2#493]
🗺️Location
-

- 삭제되는 post의 댓글의 신고를 삭제 할 때

🤷WHAT
-
어떤 문제가 발생했는지
- 삭제되어야하는 댓글 신고가 삭제되지않음

✏️HOW
-
어떻게 해결했는지
- 스케줄링 순서를 변경함
  - 댓글이 먼제 삭제되면서 '신고된 댓글(ReportedReply)' 컬럼이 ```@OnDelete(action = OnDeleteAction.SET_NULL)```로 인해 NULL 처리가 되어 reportedReply로 해당 컬럼을 찾지 못해서 삭제하지못하는 것으로 확인.

**Comment by Subak-Uncle** [comment]
Branch [bugfix/#493](https://github.com/cca-ffodregamdi/running-hi-back-v2/tree/bugfix/#493) created!
