### ISSUE TITLE
Feature - Dummy 데이터 SQL문 수정, test/data 제거

### ISSUE THREAD

**Issue by silverpoodle** [cca-ffodregamdi/running-hi-back-v2#505]
✏️Description
-
- 멤버 No 수정으로 SQL 문 최종 수정
- test/data 주석 처리

✅TODO
- [x] SQL 문 수정
- [x] 주석처리

🐾ETC
-

**Comment by Subak-Uncle** [comment]
Branch [feature/#505](https://github.com/cca-ffodregamdi/running-hi-back-v2/tree/feature/#505) created!
