### ISSUE TITLE
Feature - 회원 약관동의 컬럼, 여부 확인 API 추가

### ISSUE THREAD

**Issue by numerical43** [cca-ffodregamdi/running-hi-back-v2#510]
✏️Description
-

- 회원이 약관에 동의했는지 확인하는 API 추가
  - 여부를 확인할 수 있게 member 테이블에 약관동의와 관련된 boolean 컬럼 추가

✅TODO
- [x] 약관 동의 여부를 응답으로 보내는 API
- [x] 약관 동의 컬럼 추가 

🐾ETC
-

**Comment by Subak-Uncle** [comment]
Branch [feature/#510](https://github.com/cca-ffodregamdi/running-hi-back-v2/tree/feature/#510) created!
