### ISSUE TITLE
Refactoring - member data.sql 수정

### ISSUE THREAD

**Issue by numerical43** [cca-ffodregamdi/running-hi-back-v2#513]
✏️Description
-

- member에 컬럼이 추가됨에 따라 data.sql 수정

✅TODO
- [x] members.sql에 isTermsAgreed 추가

🐾ETC
-

**Comment by Subak-Uncle** [comment]
Branch [refactor/#513](https://github.com/cca-ffodregamdi/running-hi-back-v2/tree/refactor/#513) created!
