### ISSUE TITLE
Feature - 지역설정 여부 API

### ISSUE THREAD

**Issue by numerical43** [cca-ffodregamdi/running-hi-back-v2#515]
✏️Description
-

- 화면 진입 시 지역 설정 여부를 확인할 수 있는 API 추가

✅TODO
-
- [x] 지역설정 여부 API 추가 
- [x] 하는 김에 초기 레벨업 km 수정

🐾ETC
-

**Comment by Subak-Uncle** [comment]
Branch [feature/#515](https://github.com/cca-ffodregamdi/running-hi-back-v2/tree/feature/#515) created!
