### ISSUE TITLE
BugFix - 러닝데이터 저장 시 기록에 적용되지 않는 문제 해결

### ISSUE THREAD

**Issue by silverpoodle** [cca-ffodregamdi/running-hi-back-v2#517]
🗺️Location
-
- PostService
- RecordService

🤷WHAT
-
- 러닝 기록 저장 시 기록에 적용되지 않는 문제 해결

✅TODO
- [x] 기록 저장

🐾ETC
-

**Comment by Subak-Uncle** [comment]
Branch [bugfix/#517](https://github.com/cca-ffodregamdi/running-hi-back-v2/tree/bugfix/#517) created!
