### ISSUE TITLE
Refactoring - 게시글 조회 시 거리 필터 설정 제거

### ISSUE THREAD

**Issue by silverpoodle** [cca-ffodregamdi/running-hi-back-v2#519]
✏️Description
-
- 출시를 위한 조회 코드 수정
- 거리 설정 제거 (좋아요, 북마크, 최신순 필터 유지)

✅TODO
- [x] PostController
- [x] PostService
- [x] PostQueryRepository

🐾ETC
-
- 빠수빠수빠수

**Comment by Subak-Uncle** [comment]
Branch [refactor/#519](https://github.com/cca-ffodregamdi/running-hi-back-v2/tree/refactor/#519) created!
