### ISSUE TITLE
BugFix - 프로필 이미지 조회 시 null 값 반환

### ISSUE THREAD

**Issue by numerical43** [cca-ffodregamdi/running-hi-back-v2#542]
🗺️Location
-

- 프로필 이미지 조회

🤷WHAT
-
어떤 문제가 발생했는지
- 프로필 이미지 조회 시 null 값이 반환되는 문제

✏️HOW
-
어떻게 해결했는지
- 더미데이터 컬럼, 값 수정

🐾ETC
-

**Comment by Subak-Uncle** [comment]
Branch [bugfix/#542](https://github.com/cca-ffodregamdi/running-hi-back-v2/tree/bugfix/#542) created!
