### ISSUE TITLE
Fix- 러닝 기록 저장 시 누적거리 설정

### ISSUE THREAD

**Issue by silverpoodle** [cca-ffodregamdi/running-hi-back-v2#547]
✏️Description
-
- 러닝 GPS 파일 저장 시 누적거리 저장 설정

✅TODO
- [x] PostService

🐾ETC
-

**Comment by Subak-Uncle** [comment]
Branch [feature/#547](https://github.com/cca-ffodregamdi/running-hi-back-v2/tree/feature/#547) created!
