### ISSUE TITLE
Refactoring - 챌린지 상태 타입 변경

### ISSUE THREAD

**Issue by hodin030** [cca-ffodregamdi/running-hi-back-v2#551]
✏️Description
-

챌린지 상태  enum 타입으로 변경 

✅TODO
- [x] SCEDULED, IN_PROGRESS, COMPLEATED (예정, 진행중, 완료) 세 가지로 enum 적용
- [x] 랭킹 조회 쿼리 방식 변경

🐾ETC
-

**Comment by Subak-Uncle** [comment]
Branch [refactor/#551](https://github.com/cca-ffodregamdi/running-hi-back-v2/tree/refactor/#551) created!
