### ISSUE TITLE
BugFix - DistanceToNextLevel 수정

### ISSUE THREAD

**Issue by silverpoodle** [cca-ffodregamdi/running-hi-back-v2#556]
🗺️Location
-
- RunDataVO

🤷WHAT
-
- 이해를 잘못해쏘용ㅎㅎ;;

✏️HOW
-
- 남은 거리 계산 공식 수정 티비

✅TODO
- [x] updateTotalDistanceKcalAndLevel

🐾ETC
-

**Comment by Subak-Uncle** [comment]
Branch [bugfix/#556](https://github.com/cca-ffodregamdi/running-hi-back-v2/tree/bugfix/#556) created!
