### ISSUE TITLE
Fix - MainData 저장 시 소수점 2자리까지만 보이도록 수정

### ISSUE THREAD

**Issue by silverpoodle** [cca-ffodregamdi/running-hi-back-v2#568]
✏️Description
-
<img width="161" alt="image" src="https://github.com/user-attachments/assets/042d2832-0331-4d03-aa23-156736008165">

- 보기 싫음 이슈ㅠㅠ

✅TODO
- [x] PostService

🐾ETC
-

**Comment by Subak-Uncle** [comment]
Branch [bugfix/#568](https://github.com/cca-ffodregamdi/running-hi-back-v2/tree/bugfix/#568) created!
