### ISSUE TITLE
Fix - 버전 형식 1.X.X 로 수정

### ISSUE THREAD

**Issue by silverpoodle** [cca-ffodregamdi/running-hi-back-v2#570]
✏️Description
-
- 버전 비교 시 1.X.X 형식으로 수정

✅TODO
- [x] test/app-review

🐾ETC
-

**Comment by Subak-Uncle** [comment]
Branch [feature/#570](https://github.com/cca-ffodregamdi/running-hi-back-v2/tree/feature/#570) created!
