### ISSUE TITLE
Hotfix - 달린 거리 KM 저장 시 소수점 2번째 자리까지 

### ISSUE THREAD

**Issue by silverpoodle** [cca-ffodregamdi/running-hi-back-v2#572]
✏️Description
-
- 달린 거리 저장 시 소수점 2번째 자리까지 (3번째 자리에서 반올림)

<img src="https://github.com/user-attachments/assets/b8fb94a3-9c01-4312-b1fc-e9a513a51f58" width="30%" alt="Image">
<img src="https://github.com/user-attachments/assets/e5c4f331-0ec6-43c5-8398-ca120734c090" width="30%" alt="Image">

✅TODO
- [x] PostService

🐾ETC
-

**Comment by Subak-Uncle** [comment]
Branch [feature/#572](https://github.com/cca-ffodregamdi/running-hi-back-v2/tree/feature/#572) created!
