### ISSUE TITLE
BugFix - 게시글(러닝 기록) 삭제 시 기록 엔티티에 적용

### ISSUE THREAD

**Issue by silverpoodle** [cca-ffodregamdi/running-hi-back-v2#579]
🗺️Location
-
- PostService: deletePost

🤷WHAT
-
- 해당하는 기록 엔티티가 삭제가 안 된 다잉

✏️HOW
-
- 해당하는 기록 엔티티 찾아서 삭제하도록 수정

✅TODO
- [x] deletePost
- [x] deleteRecord

🐾ETC
-

**Comment by Subak-Uncle** [comment]
Branch [bugfix/#579](https://github.com/cca-ffodregamdi/running-hi-back-v2/tree/bugfix/#579) created!
