### ISSUE TITLE
BugFix - RECORD dto 명칭 수정, 주간 데이터 오류 확인

### ISSUE THREAD

**Issue by silverpoodle** [cca-ffodregamdi/running-hi-back-v2#581]
🗺️Location
-
- RecordQueryRepository

🤷WHAT
-
- dto 반환 시 명칭 통일 안됨.. 개바보이슈
- 주간 데이터 이미지 관련 오류 확인 (다른 이미지로 보임)

✏️HOW
-
- 몰라 해봐야 알아!!!!

✅TODO
- [x] RecordQueryRepository
- [x] GetWeeklyRecordResponse

🐾ETC
-

**Comment by Subak-Uncle** [comment]
Branch [bugfix/#581](https://github.com/cca-ffodregamdi/running-hi-back-v2/tree/bugfix/#581) created!
