### ISSUE TITLE
BugFix - 기록탭 러닝횟수 오류(중복 카운팅) 수정

### ISSUE THREAD

**Issue by silverpoodle** [cca-ffodregamdi/running-hi-back-v2#583]
🗺️Location
-
- 기록탭 러닝횟수 수정

🤷WHAT
-
- 하루에 2번 이상 뛸 경우 중복으로 카운팅

✏️HOW
-
- RecordResponse 에 totalCnt 추가

✅TODO
- [x] RecordQueryRepository
- [x] WeeklyRecordResponse
- [x] MonthlyRecordResponse
- [x] YearlyRecordResponse

🐾ETC
-

**Comment by Subak-Uncle** [comment]
Branch [bugfix/#583](https://github.com/cca-ffodregamdi/running-hi-back-v2/tree/bugfix/#583) created!
