### ISSUE TITLE
Feature - 게시글 상세보기 response 에 mainDataType 추가

### ISSUE THREAD

**Issue by silverpoodle** [cca-ffodregamdi/running-hi-back-v2#584]
✏️Description
-
- 게시글 수정 시 적용 가능하도록 response mainData (int 형) 추가

✅TODO
- [x] Post Entity 칼럼 추가
- [x] PostResponse mainData 추가

🐾ETC
-

**Comment by Subak-Uncle** [comment]
Branch [feature/#584](https://github.com/cca-ffodregamdi/running-hi-back-v2/tree/feature/#584) created!
