### ISSUE TITLE
BugFix - 프로필 이미지 수정, 삭제 오류

### ISSUE THREAD

**Issue by numerical43** [cca-ffodregamdi/running-hi-back-v2#593]
🗺️Location
-

- 프로필 이미지 수정, 프로필 이미지 삭제 시

🤷WHAT
-
어떤 문제가 발생했는지
- 이미지 수정/삭제가 진행이 안되고 500 에러 발생

✏️HOW
-
어떻게 해결했는지
- Image 도메인에 프로필 이미지도 같이 저장된다고 생각해서 ImageRepository로 이미지 삭제 시도 
   -> Image 도메인에는 포스트와 관련된 imageUrl밖에 없기 때문에 db에 존재하지않는다는 에러 발생
- Imga 도메인이 아니라 Storage에서만 이미지를 삭제하도록 수정

✅ TODO
- [ ] 프로필 이미지 수정/삭제 로직 수정

🐾ETC
-

**Comment by Subak-Uncle** [comment]
Branch [bugfix/#593](https://github.com/cca-ffodregamdi/running-hi-back-v2/tree/bugfix/#593) created!
