### ISSUE TITLE
BugFix - 앱 버전 오류 수정

### ISSUE THREAD

**Issue by hodin030** [cca-ffodregamdi/running-hi-back-v2#596]
🗺️Location
-

/test/app-review

🤷WHAT
-
새로운 앱 버전과 서버에 등록된 버전이 맞지 않아 테스트 로그인 화면 뜸

✏️HOW
-
서버에 등록된 버전을 1.0.2로 수정

✅TODO
- [x] yml에 등록된 버전을 1.0.2로 수정

🐾ETC
-

**Comment by Subak-Uncle** [comment]
Branch [bugfix/#596](https://github.com/cca-ffodregamdi/running-hi-back-v2/tree/bugfix/#596) created!
