### ISSUE TITLE
Test - POST 도메인 테스트 코드 작성 

### ISSUE THREAD

**Issue by silverpoodle** [cca-ffodregamdi/running-hi-back-v2#598]
✏️Description
-
늦어서 죄송합니다리..

✅TODO
- [ ] PostServiceTests
- [ ] PostControllerTests

🐾ETC
-

**Comment by Subak-Uncle** [comment]
Branch [test/#598](https://github.com/cca-ffodregamdi/running-hi-back-v2/tree/test/#598) created!
