### ISSUE TITLE
BugFix - mainData 수정 시 mainDataType 적용 누락 수정

### ISSUE THREAD

**Issue by silverpoodle** [cca-ffodregamdi/running-hi-back-v2#600]
🗺️Location
-
- POST 수정

🤷WHAT
-
- mainData 수정 시 mainDataType 적용 누락 수정

✏️HOW
-
- update  수정

✅TODO
- [x] PostService

🐾ETC
-

**Comment by Subak-Uncle** [comment]
Branch [bugfix/#600](https://github.com/cca-ffodregamdi/running-hi-back-v2/tree/bugfix/#600) created!
