### ISSUE TITLE
BugFix - 기록 페이지 게시글 조회 누락 오류 수정

### ISSUE THREAD

**Issue by silverpoodle** [cca-ffodregamdi/running-hi-back-v2#608]
🗺️Location
-
- 으아아아!
- 기록 조회 시 게시글 리스트

🤷WHAT
-
- 몇몇개가 누락 됩니다잉

✏️HOW
-
- 모르겟어요잉! 봐보겠수다

✅TODO
- [ ] GetWeeklyRecord
- [ ] GetMonthlyRecord
- [ ] GetYearlyRecord

🐾ETC
-

**Comment by Subak-Uncle** [comment]
Branch [bugfix/#608](https://github.com/cca-ffodregamdi/running-hi-back-v2/tree/bugfix/#608) created!

**Comment by Subak-Uncle** [comment]
😎😎
