### ISSUE TITLE
Feature - 나의 게시글 조회시 공유된 게시글만 조회되도록 수정

### ISSUE THREAD

**Issue by silverpoodle** [cca-ffodregamdi/running-hi-back-v2#609]
✏️Description
-
- 나의 게시글 조회시 `status = true` 인 게시글만 조회되도록 수정

✅TODO
- [x] GetMyPosts

🐾ETC
-

**Comment by Subak-Uncle** [comment]
Branch [feature/#609](https://github.com/cca-ffodregamdi/running-hi-back-v2/tree/feature/#609) created!
