### ISSUE TITLE
BugFix - 피드 댓글 갯수에서 삭제된 댓글 카운트 되는 버그 발견!

### ISSUE THREAD

**Issue by Subak-Uncle** [cca-ffodregamdi/running-hi-back-v2#613]
🗺️Location
- GET - `/api/posts/only/{postNo}'

🤷WHAT
- 댓글은 완전 삭제가 아닌 상태값으로 구분합니다.
- 삭제된 댓글까지 count에 들어가는 상황입니다.

✏️HOW
- 삭제된 댓글들은 집계에 들어가지 않도록 수정하였습니다.

🐾ETC
-

**Comment by Subak-Uncle** [comment]
Branch [bugfix/#613](https://github.com/cca-ffodregamdi/running-hi-back-v2/tree/bugfix/#613) created!

**Comment by silverpoodle** [comment]
시러리, 시러리, 시러리시러리, 시러리.

**Comment by Subak-Uncle** [comment]
머가 시러리. 모가 쉬러뤼. 머머가가 시러리!
